name: "Hello World"
description: "Says hello and prints the current time"
author: "Your Name"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The current time.."
runs:
  using: "node20"
  main: "index.js"
